#index:
#    path: /
#    controller: App\Controller\DefaultController::index

gitrepo_page:
  path: /hello
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'gitrepo.html.twig'